### ISSUE TITLE
package.json or bpkg.json

### ISSUE THREAD

**Issue by sinkcup** [bpkg/bpkg#137] opened 2021-08-14 02:07 UTC
![image](https://user-images.githubusercontent.com/4971414/129431282-aa68678a-c13e-4316-86f0-8e9eb5a33e44.png)
![image](https://user-images.githubusercontent.com/4971414/129431270-27e595b6-79fd-44a2-ad7a-d48b7f5f7d8f.png)
![image](https://user-images.githubusercontent.com/4971414/129431289-2f3eccc9-a47d-4ac4-ad76-1147b249a1cb.png)

**Comment by Potherca** [comment] 2021-08-15 12:40
Looks like this was caused by the work for supporting `bpkg.json` was merged to the `develop` branch (for preliminary testing) but not yet released to master. The documentation changes _were_ already released, causing this confusion.

I think the best way to resolve this would be to merge the changes (from #132) into master...

**Comment by Potherca** [comment] 2022-03-27 14:50
Closing this as #132 has been merged (via #140).

It should be `bpkg.json` everywhere. Any mention of `package.json` other than as an extra/backward-compatible option should be considered incorrect/outdated.

**Closed by Potherca** 2022-03-27 14:50 UTC
