### ISSUE TITLE
bpkg install is broken since #76

### ISSUE THREAD

**Issue by seybi87** [bpkg/bpkg#118] opened 2020-01-15 09:18 UTC
Hi guys,

I tried to install bpkg via the install script in a docker container with the Ubuntu:16.04 image (as root user)

`curl -Lo- "https://raw.githubusercontent.com/bpkg/bpkg/master/setup.sh" | bash`

The install fails due to several issues:

1. It seems there is an error in the bash script:
`bash: line 64: [: ==: unary operator expected`

2. After fixing this issue manually it seems that the bpkg is not set into the path:
`bash: bpkg: command not found` as it is installed into `/root/.local/bin/bpkg`

Could you please look into this?

**Comment by seybi87** [comment] 2020-01-15 09:50
And one additional issue:

By calling bpkg via the absolute path `/root/.local/bin/bpkg` the following error message shows up:
`error: Missing bpkg-json dependency`

**Comment by jwerle** [comment] 2020-01-15 14:12
Hi @seybi87,

Thanks for reporting this issue!

> It seems there is an error in the bash script:
> `bash: line 64: [: ==: unary operator expected`

This is a simple fix and should be addressed in #119 (and #120)

> After fixing this issue manually it seems that the bpkg is not set into the path:
> `bash: bpkg: command not found as it is installed into /root/.local/bin/bpkg`

I can't seem to reproduce this in any sensible way. Can you please advise so we can work towards a solution?

**Comment by Potherca** [comment] 2020-01-15 15:58
Regarding these issues:

All these issues happen because the `$USER` variable is empty.

1. The fact that `$USER` not quoted (in ` if [ $USER == 'root' ]; then`) and the empty `$USER` causes the "unary operator expected" error.

2. As `$USER` is empty, `$USER` does not match `root`. Hence the install prefix is set to `$HOME/.local`, As `$HOME` _is_ set, we end up in `/root/.local/bin/bpkg`.

3. As `/root/.local/bin/` is most likely not in `$PATH`, `bpkg-json` can not be found there.

@seybi87 could you verify this inside the Docker container you are using? If `echo "$USER"` _does_ show `root`, that means we are (accidentally) setting it to empty somewhere in our code.

@jwerle My suggestion to fix these issues would be to double-quote `"` any unquoted variables and replace the `$USER` call (which is not guaranteed to exist) with a `whoami` call or comparison with the current user ID.

**Comment by seybi87** [comment] 2020-01-15 17:26
Hi guys, 
thanks for the quick responses.

If have just tried the latest install script on a frsh ubuntu:16.04 container.

@Potherca  per default there is not USER variable set at all and in consequnece the install script still causes problems as bpkg is not set into the path and in consequnece the ` bpkg-json dependency` will be missing as well (@Potherca  as you pointed out correctly). See the output below:
`bash: line 64: [: ==: unary operator expected
  info: Welcome to the 'bpkg' installer!
  info: Checking for git...

  info: Creating temporary files...
  info: Fetching latest 'bpkg'...
  info: Installing...

  info: Uninstalling /root/.local/bin/bpkg...
  info: Installing /root/.local/bin/bpkg...
  info: Done!`

As soon as I set the USER variable and execute the install script `bpkg` is installed as expected.

So is setting the USER variable from now on mandatory? 
If yes, having an error message and some hints in the readme would be helpful as this variable is usually not set per default in docker containers. 

Or is it intended to work with an empty USER variable?

**Comment by Potherca** [comment] 2020-01-15 18:48
> So is setting the USER variable from now on mandatory?

No, it is not. The `$USER` is guaranteed to be set (in fact, in some distros it doesn't even exist).

> Or is it intended to work with an empty USER variable?

Yes, it is. The usage of `$USER` is an oversight (or edge-case) that will have to be addressed to fix this issue.

**Comment by cha87de** [comment] 2020-01-16 10:32
The integration into the (already existing) travis-ci build could use shellcheck, e.g.
https://github.com/cha87de/bpkg/blob/master/.travis.yml

I would be happy to open a PR for that change, but the shellcheck currently fails :-/
https://travis-ci.org/cha87de/bpkg/builds/637883936

**Comment by Potherca** [comment] 2021-01-01 12:13
Closing this issue as it has been resolved through #119 and #120.

It will be released as part of v0.3.2.

**Closed by Potherca** 2021-01-01 12:13 UTC
Labels: bug
